#!/bin/bash

set -euo pipefail

exec 1>&2

if [ -f "Cargo.toml" ]
then
    export RUSTDOCFLAGS="-D warnings"

    cargo +nightly fmt    --all       --check
    cargo          clippy --workspace -- --deny warnings
    cargo          test   --workspace
    cargo          doc    --workspace
fi

# TODO: run `shellcheck` on comitted files

exit 0
