#!/bin/sh

# Based off the sample hook created by `git-init`.

# Rejects pushes containing commit messages starting with "WIP" or "TODO".

_remote="$1"
_url="$2"

regex='^TODO|WIP'

zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')

while read -r local_ref local_oid _remote_ref remote_oid
do
    if [ "$local_oid" = "$zero" ]
    then
        # Branch deleted.
        :
    else
        if [ "$remote_oid" = "$zero" ]
        then
            # New branch, examine all commits.
            range="$local_oid"
        else
            # Update to existing branch, examine new commits.
            range="$remote_oid..$local_oid"
        fi

        commit=$(git rev-list -n 1 --grep "$regex" "$range")

        if [ -n "$commit" ]
        then
            echo >&2 "Found WIP commit in $local_ref"
            exit 1
        fi
    fi
done

exit 0
